### ISSUE TITLE
Editieren nach dem Abstimmen verhindern

### ISSUE THREAD

**Issue by gernotfasching** [Max-Hierzer/Development-Diplomarbeit#1]
**Beschreibung:** Nach dem Abstimmen soll es nicht mehr möglich sein, die Umfrage zu bearbeiten.
**Ziel:** Sicherstellen, dass Benutzer ihre Abstimmung nicht mehr ändern können, sobald sie abgestimmt haben.

**Comment by Max-Hierzer** [comment]
Bug ist gefixed
