### ISSUE TITLE
Automatisches Schließen

### ISSUE THREAD

**Issue by gernotfasching** [Max-Hierzer/Development-Diplomarbeit#6]
Poll soll geschlossen werden wenn end_date erreicht wurde. Also soll dann keine Abstimmungen mehr zulassen.

Am Ende soll Ergebniss trotzdem noch anzeigbar sein.

**Comment by Max-Hierzer** [comment]
Dadurch, dass man sie nicht mehr selecten sollte dieses Issue fertig sein
