### ISSUE TITLE
Auswahl von Polls auf Funktionen aufteilen.

### ISSUE THREAD

**Issue by gernotfasching** [Max-Hierzer/Development-Diplomarbeit#7]
Je nach ausgewählter Funktion soll man verschiedene Polls auswählen können.
Wunschverhalten:
- Bei Edit sollen nur noch nicht veröffentlichte Polls auswählbar sein.
- Bei Vote sollen nur noch Polls auswählbar sein welche schon veröffentlicht sind, aber noch nicht geendet haben.
- Bei Show Results sollen nur Polls auswählbar sein die schon geendet haben.

**Comment by Max-Hierzer** [comment]
Ich werde mit Edit starten.
